X_train = [
    "Giải ngân trong 15 phút, lãi suất ưu đãi.",
    "Bạn cần chuyển 1 triệu để hoàn tất hồ sơ vay.",
    "Hệ thống yêu cầu ứng tiền trước khi giải ngân.",
    "Việc nhập liệu tại nhà, trả lương theo ngày.",
    "Tài khoản bạn phát hiện truy cập bất thường.",
    "Cứu con với, mẹ chuyển tiền cho con đi.",
    "Anh gặp tai nạn, giúp anh một ít tiền nhé.",
    "Mọi thông tin được bảo mật theo quy định.",
    "Hàng hiệu giá rẻ hơn 90%, số lượng có hạn.",
    "Cộng đồng đầu tư mới, cam kết không rủi ro.",
    "Giảm giá sốc chỉ hôm nay, mua 1 tặng 2.",
    "Liên hệ để nhận phần quà hấp dẫn trị giá hàng chục triệu.",
    "Gói đầu tư đặc biệt, hoàn vốn trong 10 ngày.",
    "Vay tiền mặt, không gặp mặt, chuyển khoản trực tiếp.",
    "Công việc nhẹ, không áp lực, thu nhập cao.",
    "Bạn là người trúng giải chương trình truyền hình.",
    "Thanh toán trước 500k để được ưu tiên xử lý.",
    "Cơ hội mua sắm tiết kiệm không thể bỏ qua.",
    "Duyệt vay trong ngày, không ràng buộc.",
    "Người quen anh bị tai nạn, anh ứng tiền trước nhé.",
    "Truy cập từ xa để hỗ trợ nâng cấp hệ thống.",
    "Gọi số hotline để được hỗ trợ vay vốn.",
    "Bạn có thể chia sẻ màn hình để được hỗ trợ?",
    "Chỉ cần điền form, tiền về tài khoản trong 1 giờ.",
    "Tham gia hệ thống tài chính thông minh, sinh lời mỗi ngày.",
    "Nộp phí cam kết để nhận ưu đãi lãi suất.",
    "Bạn có thể cài AnyDesk để tôi hỗ trợ nhanh chóng.",
    "Chúng tôi sẽ liên hệ sớm để giao hàng.",
    "Cam kết lợi nhuận 30% mỗi tháng khi tham gia.",
    "Truy cập đường dẫn sau để bảo vệ tài khoản của bạn.",
    "Anh không liên lạc được với người thân, giúp tạm.",
    "Bạn đã thắng giải đặc biệt, truy cập link để nhận thưởng.",
    "Vay nhanh 20 triệu không cần chứng minh thu nhập.",
    "Hệ thống đã tiếp nhận yêu cầu đổi trả.",
    "Giải thưởng đang chờ bạn, xác nhận ngay hôm nay.",
    "Chúc mừng, bạn đã được chọn nhận quà miễn phí.",
    "Khoản vay dành riêng cho khách hàng thân thiết.",
    "Đăng ký ngay để nhận công việc làm thêm tại nhà.",
    "Bạn cần thanh toán phí tư vấn để tiếp tục.",
    "Xin cảm ơn vì đã sử dụng dịch vụ của chúng tôi.",
    "Máy tính bạn có dấu hiệu bị xâm nhập, cần kiểm tra.",
    "Bạn có thể theo dõi đơn hàng qua email.",
    "Không cần kinh nghiệm, vẫn có thể kiếm 15 triệu/tháng.",
    "Chỉ còn vài suất ưu đãi cuối cùng.",
    "Tài khoản bạn bị tạm khóa, nhấn vào đây để mở lại.",
    "Bạn là người may mắn nhất, nhận ngay giải thưởng khủng.",
    "Phần thưởng 100 triệu đã sẵn sàng cho bạn.",
    "Đầu tư vào cổ phiếu mới nổi, lợi nhuận cao.",
    "Em bị giật điện thoại, cần mượn tiền về.",
    "Đăng ký tài khoản đầu tư và nhận ngay 1 triệu đồng.",
    "Trúng thưởng xe SH, vui lòng xác nhận thông tin nhận giải.",
    "Điện thoại iPhone giá chỉ còn 3 triệu.",
    "Chuyển khoản giữ đơn, ship toàn quốc.",
    "Việc làm cho học sinh, sinh viên, linh hoạt thời gian.",
    "Chuyển khoản xác nhận thanh toán hợp đồng.",
    "Đặc biệt giảm thêm cho khách chuyển khoản.",
    "Việc gấp, chỉ cần chuyển khoản giữ chỗ.",
    "Tham gia nhóm VIP để được tư vấn đầu tư lãi cao.",
    "Con bị giữ ở trường, chuyển tiền đóng phạt gấp.",
    "Đặt hàng trước để giữ giá tốt nhất.",
    "Để tiếp tục sử dụng, hãy chạy phần mềm theo link.",
    "Email cảnh báo bảo mật, yêu cầu xác thực gấp.",
    "Tình hình gấp, không gọi được, nhắn tin giúp anh.",
    "Mua ngay hôm nay để nhận quà miễn phí.",
    "Mẹ đang ở bệnh viện, con chuyển tiền gấp.",
    "Không cần vốn lớn, vẫn có thể đầu tư sinh lời.",
    "Hẹn bạn ngày mai để bàn giao sản phẩm.",
    "Hợp tác cùng chuyên gia tài chính, lợi nhuận đảm bảo.",
    "Chuyển gấp 2 triệu, em sẽ kể sau.",
    "Chỉ cần CMND là có thể vay ngay hôm nay.",
    "Tư vấn vay miễn phí, không mất phí xử lý.",
    "Chúng tôi cam kết bảo hành đúng quy trình.",
    "Click vào đây để xác nhận email đăng ký.",
    "Chúng tôi phát hiện lỗi hệ thống, cần bạn xác nhận.",
    "Liên hệ đội ngũ kỹ thuật để xử lý sự cố gấp.",
    "Chỉ cần điện thoại, có thể làm việc ở bất cứ đâu.",
    "Khuyến mãi khủng, giá hủy diệt, đừng bỏ lỡ.",
    "Bạn trúng thưởng kỳ quay số gần nhất.",
    "Thông tin tài khoản đã hết hạn, vui lòng cập nhật.",
    "Vui lòng nộp phí đăng ký qua Momo.",
    "Cần tuyển gấp nhân viên online, lương hấp dẫn.",
    "Chuyển tiền giữ chỗ để được xét duyệt hồ sơ.",
    "Làm việc online, nhận lương qua ví điện tử.",
    "Đóng phí bảo hiểm trước khi nhận khoản vay.",
    "Máy tính bạn bị treo vì virus, cần xử lý ngay.",
    "Không cần tài sản đảm bảo, vay được ngay.",
    "Ngân hàng yêu cầu xác minh lại thông tin cá nhân.",
    "Chúc bạn một ngày làm việc hiệu quả.",
    "Ứng tuyển ngay hôm nay để nhận việc đầu tuần.",
    "Xác nhận mật khẩu mới để tránh mất tài khoản.",
    "Cơ hội làm giàu với đầu tư tiền điện tử.",
    "Ba bị ngã, cần tiền làm thủ tục nhập viện.",
    "Phát hiện mã độc, vui lòng cho phép truy cập.",
    "Bạn cần cung cấp mã OTP để tiếp tục sử dụng dịch vụ.",
    "Tôi là nhân viên kỹ thuật, hãy cài phần mềm này.",
    "Ứng trước phí dịch vụ để được hỗ trợ nhanh.",
    "Bạn đã giành chiến thắng giải quay số điện tử.",
    "Đơn hàng của bạn đã được tiếp nhận.",
    "Hệ thống cần bạn cập nhật thông tin bảo mật.",
    "Thông tin khách hàng đã được cập nhật."
]

y_train = [
    "tin_dung",
    "tai_chinh",
    "tai_chinh",
    "viec_lam",
    "phishing",
    "gia_mao_nguoi_than",
    "gia_mao_nguoi_than",
    "hop_le",
    "mua_sam",
    "dau_tu",
    "mua_sam",
    "trung_thuong",
    "dau_tu",
    "tin_dung",
    "viec_lam",
    "trung_thuong",
    "tai_chinh",
    "mua_sam",
    "tin_dung",
    "gia_mao_nguoi_than",
    "ho_tro",
    "tin_dung",
    "ho_tro",
    "tin_dung",
    "dau_tu",
    "tai_chinh",
    "ho_tro",
    "hop_le",
    "dau_tu",
    "phishing",
    "gia_mao_nguoi_than",
    "trung_thuong",
    "tin_dung",
    "hop_le",
    "trung_thuong",
    "trung_thuong",
    "tin_dung",
    "viec_lam",
    "tai_chinh",
    "hop_le",
    "ho_tro",
    "hop_le",
    "viec_lam",
    "mua_sam",
    "phishing",
    "trung_thuong",
    "trung_thuong",
    "dau_tu",
    "gia_mao_nguoi_than",
    "dau_tu",
    "trung_thuong",
    "mua_sam",
    "mua_sam",
    "viec_lam",
    "tai_chinh",
    "mua_sam",
    "viec_lam",
    "dau_tu",
    "gia_mao_nguoi_than",
    "mua_sam",
    "ho_tro",
    "phishing",
    "gia_mao_nguoi_than",
    "mua_sam",
    "gia_mao_nguoi_than",
    "dau_tu",
    "hop_le",
    "dau_tu",
    "gia_mao_nguoi_than",
    "tin_dung",
    "tin_dung",
    "hop_le",
    "phishing",
    "ho_tro",
    "ho_tro",
    "viec_lam",
    "mua_sam",
    "trung_thuong",
    "phishing",
    "tai_chinh",
    "viec_lam",
    "tai_chinh",
    "viec_lam",
    "tai_chinh",
    "ho_tro",
    "tin_dung",
    "phishing",
    "hop_le",
    "viec_lam",
    "phishing",
    "dau_tu",
    "gia_mao_nguoi_than",
    "ho_tro",
    "phishing",
    "ho_tro",
    "tai_chinh",
    "trung_thuong",
    "hop_le",
    "phishing",
    "hop_le"
]